import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    CreateDateColumn,
    UpdateDateColumn,
    ManyToOne,
    JoinColumn,
    Index,
} from 'typeorm';
import { Phase } from './phase.entity';

// ─── Enums ───────────────────────────────────────────────────

export enum ContentFormat {
    REEL      = 'reel',
    CAROUSEL  = 'carousel',
    STORY     = 'story',
    POST      = 'post',
}

export enum CtaType {
    SOFT        = 'soft',
    HARD        = 'hard',
    EDUCATIONAL = 'educational',
}

export enum ContentBlockStatus {
    DRAFT     = 'draft',
    SCHEDULED = 'scheduled',
    EDITED    = 'edited',
}

// ─── Entity ──────────────────────────────────────────────────

@Entity('content_blocks')
@Index(['phaseId'])
export class ContentBlock {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ name: 'phase_id' })
    phaseId: string;

    @ManyToOne(() => Phase, (phase) => phase.contentBlocks, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'phase_id' })
    phase: Phase;

    /** Post idea title generated by AI */
    @Column({ length: 300 })
    title: string;

    /** Which brand pillar this content serves */
    @Column({ length: 100 })
    pillar: string;

    /** Optional MongoDB ObjectId of a specific product */
    @Column({ name: 'product_id', nullable: true, length: 24 })
    productId: string | null;

    @Column({ type: 'enum', enum: ContentFormat })
    format: ContentFormat;

    @Column({ name: 'cta_type', type: 'enum', enum: CtaType })
    ctaType: CtaType;

    /** Psychological hook e.g. "curiosity", "fear of missing out", "aspiration" */
    @Column({ name: 'emotional_trigger', nullable: true, length: 200 })
    emotionalTrigger: string | null;

    /**
     * Days from the phase start date (0 = first day of the week).
     * Used by the calendar converter to compute absolute dates.
     */
    @Column({ name: 'recommended_day_offset', default: 0 })
    recommendedDayOffset: number;

    /** e.g. "18:00" */
    @Column({ name: 'recommended_time', nullable: true, length: 10 })
    recommendedTime: string | null;

    @Column({
        type: 'enum',
        enum: ContentBlockStatus,
        default: ContentBlockStatus.DRAFT,
    })
    status: ContentBlockStatus;

    @CreateDateColumn({ name: 'created_at' })
    createdAt: Date;

    @UpdateDateColumn({ name: 'updated_at' })
    updatedAt: Date;
}
